articles/urls.py
from django.urls import path

from articles.views import ArticleListView, ArticleDetailView, \
    ArticleCreateView, ArticleUpdateView, ArticleDeleteView

urlpatterns = [
    path(
        route='',
        view=ArticleListView.as_view(),
        name='article_list'
    ),
    path(
        route='details/<int:pk>',
        view=ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        route='new/',
        view=ArticleCreateView.as_view(),
        name='article_new'
    ),
    path(
        route='edit/<int:pk>',
        view=ArticleUpdateView.as_view(),
        name='article_edit'
    ),
    path(
        route='delete/<int:pk>',
        view=ArticleDeleteView.as_view(),
        name='article_delete'
    )
]

newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('articles/', include('articles.urls'))
]

pages/urls.py
from django.urls import path

from pages.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    """
    A model that represents a newspaper article.

    Attributes:
        title: The title of the article.
        body: The body or content of the article.
        date: The article creation date and time.
        author: The user who is the author of the article.
    """
    title = models.CharField(
        max_length=255
    )
    body = models.TextField()
    date = models.DateTimeField(
        auto_now_add=True
    )
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    def __str__(self):
        """
        It returns the string representation of an 'Article' object.
        :return: The title of the article.
        """
        return self.title

    def get_absolute_url(self):
        """
        It returns the absolute URL of the detail page for an Article object.
        :return: The absolute URL of the detail page for the article.
        """
        article_detail_url = reverse(
            viewname='article_detail',
            kwargs={
                'pk': self.pk
            }
        )
        return article_detail_url


class Comment(models.Model):
    """
    A model that represents a comment made on a newspaper article.
    """
    comment = models.CharField(
        max_length=150
    )
    article = models.ForeignKey(
        to=Article,
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    def __str__(self):
        """
        It returns the string representation of a 'Comment' object.
        :return: The comment content.
        """
        return self.comment

    def get_absolute_url(self):
        """
        It returns the absolute URL of the Article list.
        :return: The absolute URL for the article list.
        """
        return reverse(viewname='article_list')

articles/forms.py
from django import forms

from articles.models import Comment


class CommentForm(forms.ModelForm):
    """
    It is a form for creating comments on articles.

    This form is 'Comment' model-based and only includes a field for the
    comment text and can be used to create new comments on an article.
    """
    class Meta:
        """
        Metadata for the CommentForm.

        Attributes:
            model (Comment): The model that the form is based.
            fields (tuple): The model fields included in the form.
        """
        model = Comment
        fields = ('comment', )

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, FormView, CreateView, \
    UpdateView, DeleteView
from django.views.generic.detail import SingleObjectMixin

from articles.forms import CommentForm
from articles.models import Article


class ArticleListView(LoginRequiredMixin, ListView):
    """
    A class-based view in Django that displays a list of "Article" objects.

    This view requires the user to be logged in (via the "LoginRequiredMixin"
    mixin) and uses the template "article_list.html" to render the list of
    articles.

    Attributes:
        model: The model that the view is using.
        template_name: The template name used to render the view.
    """
    model = Article
    template_name = 'articles/article_list.html'


class ArticleDetailGet(DetailView):
    """
    A class-based view in Django that displays the details of a
    single "Article" object.

    This view renders the details of the article and includes a form for
    adding comments to it.

    Attributes:
        model: The model that the view is using.
        template_name: The template name used to render the view.

    """
    model = Article
    template_name = 'articles/article_detail.html'

    def get_context_data(self, **kwargs):
        """
        This method adds a 'CommentForm' form object (for adding comments
        in articles) to the context data passed to the template when rendering
        the view.

        :param kwargs: Additional keywords arguments.
        :return: This method returns a dictionary with the context data used
            in the template rendering.
        """
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


class ArticleDetailPost(SingleObjectMixin, FormView):
    """
    A class-based view in Django that handles form submission for adding
    comments to a single "Article" object.

    This view uses the 'SingleObjectMixin' to retrieve the commented
    'Article' object and the 'CommentForm' form to handle comment submissions.

    Attributes:
        model: The model that the view is using.
        form_class: The form class to use for handling the comment submission.
        template_name: The template name used to render the view.
    """
    model = Article
    form_class = CommentForm
    template_name = 'articles/article_detail.html'

    def post(self, request, *args, **kwargs):
        """
        This method handles POST requests for the view, retrieving the
        'Article' object being commented on and calling its parent's
        implementation.

        :param request: The incoming request.
        :param args: Positional arguments.
        :param kwargs: Keyword arguments.
        :return: The HTTP response.
        """
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """
        A method called when the form submission is valid.

        It attaches the article and the comment author (authenticated user)
        to the comment and saves it to the database. It then calls the parent's
        implementation of the method.

        :param form: The form being submitted.
        :return: The HTTP response.
        """
        comment = form.save(commit=False)
        comment.article = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        """
        This method returns the URL for the detail page of the commented
        article after successful comment form submission.

        :return: It returns the URL for the detail page of the
            commented article.
        """
        article = self.get_object()
        success_url = reverse(
            viewname='article_detail',
            kwargs={
                'pk': article.pk
            }
        )
        return success_url


class ArticleDetailView(LoginRequiredMixin, View):
    """
    A class-based view in Django that handles both GET and POST requests for the detail page of an 'Article' object.

    This view requires the user to be logged in (via the 'LoginRequiredMixin'
    mixin) and uses the 'ArticleDetailGet' and 'ArticleDetailPost' views
    to handle the GET and POST requests, respectively.
    """

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests for the view.

        This method calls the 'ArticleDetailGet' view to handle the request.

        :param request: The incoming GET request.
        :param args: Positional arguments.
        :param kwargs: Keyword arguments.
        :return: The HTTP response.n:
        """
        view = ArticleDetailGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests for the view.

        This method calls the 'ArticleDetailPost' view to handle the request.

        :param request: The incoming POST request.
        :param args: Positional arguments.
        :param kwargs: Keyword arguments.
        :return: The HTTP response.
        """
        view = ArticleDetailPost.as_view()
        return view(request, *args, **kwargs)


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """
    A class-based view for creating a new article.

    This view extends the Django 'LoginRequiredMixin' mixin to ensure that
    only authenticated users can access it. It also uses the built-in Django
    generic view 'CreateView' to handle the creation of a new article instance.

    Attributes:
        model: The model to use for the view.
        fields: The model fields to display in the form for creating a new
            article instance.
        template_name: The name of the template to use for the view.
    """
    model = Article
    fields = ('title', 'body')
    template_name = 'articles/article_new.html'

    def form_valid(self, form):
        """
        A method called when the form submission is valid.

        This method adds the authenticated user as the article's author
        before saving the form to the database.

        It then calls the parent's implementation of the method.

        :param form: The form being submitted.
        :return: The HTTP response.
        """
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    A class-based view for updating an article.

    This view extends the Django's 'LoginRequiredMixin' mixin to ensure
    that only authenticated users can access it and the
    'UserPassesTestMixin' mixin to ensure that only the author of an
    article can edit its info. It also uses the built-in Django generic
    view 'UpdateView' to handle the update of an existing article.

    Attributes:
        model: The model to use for the view.
        fields: The model fields to display in the form for updating an article.
        template_name: The name of the template to use for the view.
    """
    model = Article
    fields = ('title', 'body')
    template_name = 'articles/article_edit.html'

    def test_func(self):
        """
        A test method to check if the current user is the article author.

        The method checks if the current authenticated user is the article
        author by comparing it with the 'obj.author' (obj is the instance of
        the article to be updated).

        :return: True, if the current authenticated user is the article author,
            False otherwise.
        """
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    A class-based view for deleting an article.

    This view extends the Django's 'LoginRequiredMixin' mixin to ensure that
    only authenticated users can access it and the 'UserPassesTestMixin'
    mixin to ensure that only the author of an article can delete it.
    It also uses the built-in Django generic view 'DeleteView' to handle
    the article deletion process.

    Attributes:
        - model: The model to use for the view.
        - template_name: The name of the template to use for the view.
        - success_url: The success URL of an article deletion.
    """
    model = Article
    template_name = 'articles/article_delete.html'
    success_url = reverse_lazy('article_list')

    def test_func(self):
        """
        A test method to check if the current user is the article author.

        The method checks if the current authenticated user is the article
        author by comparing it with the 'obj.author' (obj is the instance of
        the article to be updated).

        :return: True, if the current authenticated user is the article author,
            False otherwise.
        """
        obj = self.get_object()
        return obj.author == self.request.user

templates/articles/article_delete.html
{% extends 'layout/base.html' %}

{% block title %}Delete Article{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="col">
                <h1 class="text-center">Confirm Article Deletion</h1>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-8 d-flex justify-content-center">
                <form class="form" method="post">
                    {% csrf_token %}
                    <p class="text-center">Are you sure you want to delete this article?</p>
                    <div class="d-flex justify-content-center mt-2">
                        <input class="btn btn-primary" type="submit" value="Confirm">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/article_detail.html
{% extends 'layout/base.html' %}
{% load crispy_forms_filters %}

{% block title %}Article Details{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="text-center mt-3">Article Details</h1>
            </div>
        </div>
        <div class="row mt-3 justify-content-center">
            <div class="col-md-10">
               <table class="table table-hover table-warning">
                   <tr>
                       <th>Title</th>
                       <td>{{ article.title }}</td>
                   </tr>
                   <tr>
                       <th>Author</th>
                       <td>{{ article.author }}</td>
                   </tr>
                   <tr>
                       <th>Creation Date</th>
                       <td>{{ article.date }}</td>
                   </tr>
                   <tr>
                       <th>Content</th>
                       <td>{{ article.body }}</td>
                   </tr>
               </table>
            </div>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-md-10">
                <h3>Comments</h3>
            </div>
        </div>
        <div class="row mt-2 mb-4 justify-content-center">
            <div class="col-md-10">
                {% if not article.comment_set.all %}
                    <h5 class="text-muted">No comments yet</h5>
                {% endif %}
                <div class="row row-cols-1 g-2">
                    {% for comment in article.comment_set.all %}
                        <div class="col">
                            <div class="card b-4 border-dark h-100">
                                <div class="card-body">
                                    <h5 class="card-title">{{ comment.author }}</h5>
                                    <p class="card-text">{{ comment }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-md-10">
                <h5>Add a comment</h5>
            </div>
        </div>
        <div class="row mt-2 mb-3 justify-content-center">
            <div class="col-md-6">
                <div class="card b-4 border-dark">
                    <div class="card-body">
                        <form action="" class="form" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-primary" type="submit">Save</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
        <div class="row mt-2 mb-3 justify-content-center">
            <div class="col-md-10">
                <div class="d-grid gap-4 d-md-block justify-content-center" role="group">
                    {% if article.author == user%}
                        <a href="{% url 'article_edit' pk=article.pk %}" class="btn btn-warning">Edit</a>
                        <a href="{% url 'article_delete' pk=article.pk %}" class="btn btn-danger">Delete</a>
                    {% endif %}
                    <a href="{% url 'article_list' %}" class="btn btn-success">Article List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/article_edit.html
{% extends 'layout/base.html' %}
{% load crispy_forms_filters %}

{% block title %}Article Update{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="col">
                <h1 class="text-center">Article Update</h1>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-8 d-flex justify-content-center">
                {% include 'articles/partials/form.html' with form=form text='Update' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/article_list.html
{% extends 'layout/base.html' %}

{% block title %}Article List{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="col">
                <h1 class="text-center">Articles</h1>
            </div>
        </div>
        {% if not article_list %}
            <div class="row mt-5">
                <div class="col">
                    <h3 class="text-center text-muted">No articles yet</h3>
                </div>
            </div>
        {% endif %}
        <div class="row row-cols-1 row-cols-md-3 g-4 mt-2">
            {% for article in article_list %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ article.title }}</h5>
                            <h6 class="card-text text-muted">{{ article.author }} | {{ article.date }}</h6>
                            <p class="card-text">{{ article.body }}</p>
                        </div>
                        <div class="card-footer d-flex justify-content-center">
                            <div class="d-grid gap-4 d-md-block justify-content-center" role="group" aria-label="Basic mixed styles example">
                                <a href="{% url 'article_detail' pk=article.pk %}" class="btn btn-success">Details</a>
                                {% if article.author == user %}
                                    <a href="{% url 'article_edit' pk=article.pk %}" class="btn btn-warning">Edit</a>
                                    <a href="{% url 'article_delete' pk=article.pk %}" class="btn btn-danger">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/articles/article_new.html
{% extends 'layout/base.html' %}
{% load crispy_forms_filters %}

{% block title %}New Article{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="col">
                <h1 class="text-center">New article</h1>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-8 d-flex justify-content-center">
                {% include 'articles/partials/form.html' with form=form text='Save' %}
            </div>
        </div>
    </div>
{% endblock %}